import type { PlanDetails } from '../types/subscription.types';

export const PLANS: Record<'pessoal' | 'obra', PlanDetails> = {
  obra: {
    id: 'obra',
    name: 'Gestão Completa Pro',
    badge: 'Tudo Incluso',
    description: 'Acesso total a Custos de Obra e Finanças Pessoais, com múltiplos ambientes ilimitados.',
    monthlyPrice: 14.90,
    yearlyPrice: 149.00,
    monthlyPriceId: 'price_1ULUVf5lB4YKiaC4GTHllWl9',
    yearlyPriceId: 'price_1ULUVn5lB4YKiaC4PYsS9S26',
    promoDiscountPercent: 50,
    promoDiscountMonths: 2,
    promoMonthlyPrice: 7.45,
    promoCouponId: 'PROMO50_2M',
    monthlyPaymentLink: 'https://buy.stripe.com/aFafZacpO4rN9fM6ZvbII00',
    yearlyPaymentLink: 'https://buy.stripe.com/4gMaEQdtS2jFgIe2JfbII01',
    features: [
      { title: 'Ambientes nativos de Custo de Obra & Reformas', included: true },
      { title: 'Ambientes nativos de Finanças Pessoais', included: true },
      { title: 'Criação de novos Ambientes e Projetos ilimitados', included: true },
      { title: 'Categorias customizadas ilimitadas criadas na hora', included: true },
      { title: 'Upload de Comprovantes e Notas no Storage', included: true },
      { title: 'Métricas de Custo por M² e Evolução Física', included: true },
      { title: 'Painel Executivo e Relatórios em Tempo Real', included: true },
      { title: 'Isolamento estrito de dados via PostgreSQL RLS', included: true },
    ],
  },
  pessoal: {
    id: 'pessoal',
    name: 'Gestão Completa Pro',
    badge: 'Tudo Incluso',
    description: 'Acesso total a Custos de Obra e Finanças Pessoais, com múltiplos ambientes ilimitados.',
    monthlyPrice: 14.90,
    yearlyPrice: 149.00,
    monthlyPriceId: 'price_1ULUVf5lB4YKiaC4GTHllWl9',
    yearlyPriceId: 'price_1ULUVn5lB4YKiaC4PYsS9S26',
    promoDiscountPercent: 50,
    promoDiscountMonths: 2,
    promoMonthlyPrice: 7.45,
    promoCouponId: 'PROMO50_2M',
    monthlyPaymentLink: 'https://buy.stripe.com/aFafZacpO4rN9fM6ZvbII00',
    yearlyPaymentLink: 'https://buy.stripe.com/4gMaEQdtS2jFgIe2JfbII01',
    features: [
      { title: 'Ambientes nativos de Custo de Obra & Reformas', included: true },
      { title: 'Ambientes nativos de Finanças Pessoais', included: true },
      { title: 'Criação de novos Ambientes e Projetos ilimitados', included: true },
      { title: 'Categorias customizadas ilimitadas criadas na hora', included: true },
      { title: 'Upload de Comprovantes e Notas no Storage', included: true },
      { title: 'Métricas de Custo por M² e Evolução Física', included: true },
      { title: 'Painel Executivo e Relatórios em Tempo Real', included: true },
      { title: 'Isolamento estrito de dados via PostgreSQL RLS', included: true },
    ],
  },
};
